[package]
name = "guessing_game"
version = "0.1.0"
authors = ["飘辰 <piaochen.xing@trustbe.cn>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

