[package]
name = "hello_crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
blake2 = "0.10.4"
hex-literal = "0.3"
aes = "0.8.1"
cipher = "0.4.2"
